server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force-response: true
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: FC2Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.187:3306/fc2_service_test
    username: fc2_service_test
    password: fc2_se@nmhta3tg
  #    username: fc2_service
  #    password: fc2_se@trx2mnsi
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  threads:
    virtual:
      enabled: true
jimmer:
  language: kotlin
  show-sql: true