server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: FC2Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.187:3306/fc2_service
    username: fc2_service
    password: fc2_se@trx2mnsi
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
jimmer:
  language: kotlin
  show-sql: true